CREATE DATABASE FACTURAS;
USE FACTURAS;

CREATE TABLE COMPRADORES
(
	CIF_Comprador VARCHAR(11),
	Nombre_Social VARCHAR(30),
	Domicilio_Social VARCHAR(30),
	Localidad VARCHAR(30),
	C_Postal VARCHAR(5),
	Telefono VARCHAR(9) NOT NULL,
	CONSTRAINT PK_COMPRADORES_CIF PRIMARY KEY(CIF_Comprador),
	CONSTRAINT UQ_COMPRADORES_NOMBRE_SOCIAL UNIQUE(Nombre_Social)
);

CREATE TABLE ARTICULOS
(
	Referencia_Articulo  VARCHAR(12),
	Descripcion_Articulo VARCHAR(30),
	Precio_Unidad FLOAT(6),
	IVA INT(2),
	Existencias_Actuales INT(5) DEFAULT 0,
	CONSTRAINT PK_ARTICULOS PRIMARY KEY(Referencia_Articulo),
	CHECK (IVA > 5 AND IVA < 25)
);

CREATE TABLE FACTURAS
(
	Factura_NO INT(6),
	Fecha_Factura DATE DEFAULT '2005/1/1',
	CIF_Cliente VARCHAR(11),
	CONSTRAINT PK_FACTURAS PRIMARY KEY(Factura_NO)
);

CREATE TABLE LINEAS_FACTURA
(
	Factura_NO INT(6),
	Referencia_Articulo VARCHAR(12),
	Unidades INT(3),
	CONSTRAINT PK_LINEAS_FACTURA PRIMARY KEY(Factura_NO, Referencia_Articulo),
	CONSTRAINT FK_LINEAS_FACTURAS FOREIGN KEY(Factura_NO)
		REFERENCES FACTURAS(Factura_NO) ON DELETE CASCADE,
	CONSTRAINT FK_LINEAS_ARTICULOS FOREIGN KEY(Referencia_Articulo)
		REFERENCES ARTICULOS(Referencia_Articulo)
);