			-- EJERCICIO A --

DROP DATABASE IF EXISTS MERCADITO;
CREATE DATABASE MERCADITO;
USE MERCADITO;

CREATE TABLE CLIENTE
(
	DNI INT,
	NOMBREC VARCHAR(6),
	APELLIDOS VARCHAR(10),
	DIRECCIONC VARCHAR(10)
);

ALTER TABLE CLIENTE
	ADD CONSTRAINT PK_CLIENTE_DNI PRIMARY KEY(DNI),
	MODIFY NOMBREC VARCHAR(6) DEFAULT 'PEPE',
	MODIFY APELLIDOS VARCHAR(10) NOT NULL,
	MODIFY DIRECCIONC VARCHAR(10) NOT NULL;
	
CREATE TABLE TIENDA
(
	COD_T INT,
	NOMBRET VARCHAR(8),
	DIRECCIONT VARCHAR(10),
	TELEFONO VARCHAR(10)
);

ALTER TABLE TIENDA
	ADD CONSTRAINT PK_TIENDA_COD_T PRIMARY KEY(COD_T),
	MODIFY DIRECCIONT VARCHAR(10) NULL,
	ADD CONSTRAINT CK_TIENDA_NOMBRET CHECK (NOMBRET != 'ZARA' OR NOMBRET != 'MANGO'),
	MODIFY NOMBRET VARCHAR(10) NOT NULL,
	MODIFY TELEFONO VARCHAR(10) NOT NULL;

CREATE TABLE PRODUCTO
(
	COD_P INT PRIMARY KEY,
	NOMBREP VARCHAR(8) NOT NULL,
	FAMILIA VARCHAR(8) NULL UNIQUE
);

CREATE TABLE COMPRA
(
	DNI INT,
	COD_P INT,
	COD_T INT NULL,
	UNIDADES INT,
	CONSTRAINT PK_COMPRA PRIMARY KEY(DNI, COD_P),
	CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY(DNI)
		REFERENCES CLIENTE(DNI),
	CONSTRAINT FK_COMPRA_TIENDA FOREIGN KEY(COD_T)
		REFERENCES TIENDA(COD_T),
	CONSTRAINT FK_COMPRA_PRODUCTO FOREIGN KEY(COD_P)
		REFERENCES PRODUCTO(COD_P)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

			-- EJERCICIO B --
			
ALTER TABLE COMPRA
	DROP FOREIGN KEY FK_COMPRA_PRODUCTO,
	DROP INDEX FK_COMPRA_PRODUCTO,
	DROP PRIMARY KEY,
	CHANGE COD_P NOMBREP VARCHAR(8),
	ADD CONSTRAINT PK_COMPRA PRIMARY KEY(DNI, NOMBREP);
	
ALTER TABLE PRODUCTO
	MODIFY FAMILIA VARCHAR(8) NULL UNIQUE DEFAULT 'HOGAR',
	DROP PRIMARY KEY,
	ADD CONSTRAINT PK_PRODUCTO_NOMBREP PRIMARY KEY(NOMBREP);
	
ALTER TABLE COMPRA
	ADD CONSTRAINT FK_COMPRA_PRODUCTO FOREIGN KEY(NOMBREP)
		REFERENCES PRODUCTO(NOMBREP);