USE INSTITUTO;
CREATE TABLE  PROFESORES_ASIGNATURAS
   (IDPROFESORES INT NOT NULL, 
	IDASIGNATURAS INT NOT NULL, 
	 CONSTRAINT PROFESORES_FK FOREIGN KEY (IDPROFESORES)
	  REFERENCES  PROFESORES(IDPROFESORES)
		ON DELETE CASCADE
        ON UPDATE CASCADE, 
	 CONSTRAINT ASIGNATURAS_FK FOREIGN KEY (IDASIGNATURAS)
	  REFERENCES  ASIGNATURAS(IDASIGNATURAS) 
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	 PRIMARY KEY (IDPROFESORES, IDASIGNATURAS)
   );

