			-- PARTE A --

DROP DATABASE IF EXISTS FUTBOL;
CREATE DATABASE FUTBOL;
USE FUTBOL;

CREATE TABLE EQUIPO
(
	CODE INT PRIMARY KEY,
	NOMBREE VARCHAR(6) NOT NULL,
	SEDE VARCHAR(10) NOT NULL DEFAULT 'SanSe',
	DIRECCION VARCHAR(10) NOT NULL
);

CREATE TABLE PARTIDO
(
	CODE INT,
	CODC INT,
	FECHA DATE,
	GOLES INT
);

CREATE TABLE CAMPO
(
	CODC INT PRIMARY KEY,
	NOMBREC VARCHAR(8) NOT NULL,
	CIUDAD VARCHAR(8) NULL,
	CONSTRAINT UQ_CAMPO_NOMBREC_CIUDAD UNIQUE(NOMBREC, CIUDAD)
);

ALTER TABLE PARTIDO
	ADD CONSTRAINT PK_PARTIDO PRIMARY KEY(CODE, CODC, FECHA),
	MODIFY GOLES INT NOT NULL,
	ADD CONSTRAINT CK_PARTIDO_GOLES CHECK(GOLES > 0),
	ADD CONSTRAINT FK_PARTIDO_EQUIPO FOREIGN KEY(CODE)
		REFERENCES EQUIPO(CODE)
		ON DELETE CASCADE, -- CREO QUE SERÍA OTRO, PERO NO ME ACUERDO DEL NOMBRE ASÍ QUE PONGO EN CASCADA
	ADD CONSTRAINT FK_PARTIDO_CAMPO FOREIGN KEY(CODC)
		REFERENCES CAMPO(CODC);
		
			-- PARTE B --
		
ALTER TABLE EQUIPO
	MODIFY SEDE VARCHAR(15) NULL DEFAULT 'SanSe';
	
ALTER TABLE PARTIDO
	DROP FOREIGN KEY FK_PARTIDO_EQUIPO;
	-- HABRÍA QUE ELIMINAR EL INDEX PERO AL ELIMINAR LA CLAVE, ME LO ELIMINA TAMBIÉN, COSA QUE NO DEBERÍA SOLO.
	
ALTER TABLE EQUIPO
	DROP PRIMARY KEY,
	ADD CONSTRAINT PK_EQUIPO PRIMARY KEY(NOMBREE);
	
ALTER TABLE PARTIDO
	CHANGE CODE NOMBREE VARCHAR(6),
	ADD CONSTRAINT FK_PARTIDO_EQUIPO FOREIGN KEY(NOMBREE)
		REFERENCES EQUIPO(NOMBREE)
		ON DELETE CASCADE;

