-- EJER 1 -- 
DROP FUNCTION CONDUCTORES;
DELIMITER $

CREATE FUNCTION CONDUCTORES(M CHAR(3)) RETURNS VARCHAR(6)
    BEGIN
        DECLARE NCOND INT DEFAULT 0;
        DECLARE COD CHAR DEFAULT '';
        SELECT COUNT(DISTINCT CODC) INTO NCOND
            FROM TRABAJOS
            WHERE CODM LIKE M;

        IF (NCOND > 1) THEN
            RETURN 'VARIOS';
        ELSE
            SELECT DISTINCT CODC INTO COD
                FROM TRABAJOS
                WHERE CODM LIKE M;
            RETURN COD;
        END IF;
    END $

DELIMITER ;

SELECT CONDUCTORES('M03');

-- EJER 2 --
DROP PROCEDURE PROCIU;
DELIMITER $
CREATE PROCEDURE PROCIU(IN PCIUDAD VARCHAR(15))
    BEGIN
        DECLARE MAX_COD INT DEFAULT 0;
        DECLARE COUNT_CIU INT DEFAULT 0;
        
        CREATE TABLE IF NOT EXISTS CIUDADES (
            CODC INT(3) DEFAULT 0,
            NOMCIU VARCHAR(20)
        );
        
        SELECT COUNT(DISTINCT NOMCIU) INTO COUNT_CIU 
            FROM CIUDADES
            WHERE NOMCIU LIKE PCIUDAD;

        IF(COUNT_CIU < 1) THEN
            SET MAX_COD = (SELECT MAX(CODC)
                            FROM CIUDADES) + 1;
            INSERT INTO CIUDADES
                VALUES(MAX_COD, PCIUDAD);
        END IF;
    END $

DELIMITER ;

CALL PROCIU('ZAMORA');

-- EJER 3 --
DROP PROCEDURE SUBIR_CAT;
DELIMITER $

CREATE PROCEDURE SUBIR_CAT(INOUT N INT)
    BEGIN
        DECLARE CON_COUNT INT DEFAULT 0;
        DECLARE COND CHAR(3) DEFAULT '';    
        UPDATE CONDUCTORES
            SET CATEG = CATEG + 1
            WHERE CODC IN (SELECT CODC
                            FROM TRABAJOS
                            WHERE CODM 'M01');

        SELECT COUNT(CODC) INTO CON_COUNT
            FROM TRABAJOS
            WHERE CODM 'M01';
        IF(CON_COUNT == 1) THEN
            SELECT CODC INTO COND
                FROM TRABAJOS
                WHERE CODM 'M01';
            INSERT INTO TRABAJOS
                VALUES(COND, 'M01', (SELECT CODP FROM TRABAJOS WHERE CODC LIKE COND), CURRENT_DATE, )
        END IF;
    END $

DELIMITER ;
CALL SUBIR_CAT(2);