-- EJERCICIO 19 --
-- PARA CADA FABRICA SACAR EL Nº DE PROVEEDORES QUE LA SUMINISTRAN Y LAS CANTIDADES TOTALES SUMINISTRDAS --
SELECT P.NF, COUNT(DISTINCT P.NP), SUM(P.CANTIDAD)
	FROM PED P
	GROUP BY P.NF;

-- EJERCICIO 20 --
-- PARA CADA ARTICULO OBTENER LA CANTIDAD TOTAL SUMINISTRADA, SU MEDIA Y LA MAYOR CANTIDAD SUMINISTRADA --
SELECT P.NA, SUM(P.CANTIDAD), AVG(P.CANTIDAD), MAX(P.CANTIDAD)
	FROM PED P
	GROUP BY P.NA;
	
-- EJERCICIO 21 --
-- ARTICULOS TALES QUE NINGUN OTRO TIENE TALLA MAS PEQUEÑA --
SELECT A.NA
	FROM ART A
	WHERE A.TALLA IN (SELECT MIN(A.TALLA)
						FROM ART A);

-- EJERCICIO 22 --
-- PARA CADA PROVEEDOR SACAR EL Nº DE ENVIOS REALIZADOS --
SELECT P.NP, COUNT(P.NP)
	FROM PED P
	GROUP BY P.NP;

-- EJERCICIO 23 --
-- NOMBRE DE LOS PROVEEDORES QUE REALIZAN MAS DE TRES ENVIOS --
SELECT PR.NOMP
	FROM PED P, PRO PR
	WHERE P.NP = PR.NP
	GROUP BY P.NP
	HAVING COUNT(CANTIDAD) > 3;

-- EJERCICIO 24 --
-- ARTICULOS SUMINISTRADOS A TODAS LAS FABRICAS --
SELECT P.NA
	FROM PED P
	GROUP BY P.NA
	HAVING COUNT(DISTINCT P.NF) = (SELECT COUNT(F.NF)
										FROM FAB F);

-- EJERCICIO 25 --
-- PROVEEDORES QUE SUMINISTRAN AL MENOS UN MISMO ARTICULO A TODAS LAS FABRICAS --
SELECT P.NP
	FROM PED P
	GROUP BY P.NA
	HAVING COUNT(DISTINCT P.NF) = (SELECT COUNT(F.NF)
									FROM FAB F)	;

-- EJERCICIO 26 --
-- ARTICULOS QUE SON SUMINISTRADOS A TODAS LAS FABRICAS DE MADRID --
SELECT P.NA
	FROM PED P, FAB F
	WHERE P.NF = F.NF AND F.NOMF LIKE 'MADRID'
	GROUP BY P.NA
	HAVING COUNT(DISTINCT P.NF) = (SELECT (F.NF)
										FROM FAB F
										WHERE F.NOMF LIKE 'MADRID');

-- EJERCICIO 27 --
-- FABRICAS QUE USAN TODOS LOS ARTICULOS SUMINISTRADOS POR EL PROVEEDOR P1 --
SELECT P.NF
	FROM PED P
	WHERE P.NA IN (SELECT P.NA
					FROM PED P
					WHERE P.NP LIKE 'P1')
	GROUP BY P.NF;
	HAVING COUNT(DISTINCT P.NA)	= (SELECT COUNT(DISTINCT P.NA)
									FROM PED P
									WHERE P.NP LIKE 'P1');

-- EJERCICIO 28 --
-- FABRICAS ABASTECIDAS POR TODOS LOS PROVEEDORES QUE SUMINISTRAN ALGUN ARTICULO DE COLOR AZUL --
SELECT P.NF
	FROM PED
	WHERE P.NP IN (SELECT P.NP
					FROM PED P, ART A
					WHERE P.NA = A.NA AND COLOR LIKE 'AZUL');

-- EJERCICIO 29 --
-- ARTICULO SUMINISTRADO A MAS FABRICAS --
SELECT NA
	FROM (SELECT NA, COUNT(NA) CONTADOR
			FROM PED
			GROUP BY NA) AS P
	WHERE CONTADOR IN (SELECT MAX(CONTADOR)
						FROM (SELECT NA, COUNT(NA) CONTADOR
								FROM PED
								GROUP BY NA) AS P2);

-- EJERCICIO 30 --
-- PROVEEDORES QUE REALIZAN UN NUMERO DE ENVIOS SUPERIOR A LA MEDIA --
SELECT P.NP, COUNT(P.NP)
	FROM PED P
	GROUP BY P.NP
	HAVING COUNT(P.NP) > (SELECT AVG(ENVIOS)
							FROM (SELECT COUNT(*)'ENVIOS'
									FROM PED P
									GROUP BY P.NF, P.NA) AS T1);
	

-- EJERCICIO 31 --
-- FABRICAS QUE RECIBEN UN DETERMINADO ARTICULO DE UN MAYOR NUMERO DE PROVEEDORES --
SELECT P.NF, P.NA
	FROM PED P
	GROUP BY P.NF, P.NA
	HAVING COUNT(DISTINCT P.NP) >= ALL (SELECT COUNT(DISTINCT P.NP)
											FROM PED P
											GROUP BY P.NF, P.NA);