-- EJERCICIO 17 --
-- FABRICAS QUE NO SON ABASTECIDAS DE ARTICULOS AZULES POR PROVEEDORES DE MADRID --
SELECT P.NF
	FROM PED P, ART A
	WHERE P.NA = A.NA AND A.COLOR NOT LIKE 'AZUL'
UNION
SELECT P.NF
	FROM PED P, PRO PR
	WHERE P.NP = PR.NP AND PR.CIUDADP NOT LIKE 'MADRID';

-- EJERCICIO 18 --
-- FABRICAS QUE USAN SOLO ARTICULOS QUE PUEDEN SER SUMINISTRADOS POR P1 --
SELECT DISTINCT P.NF
	FROM PED P
	WHERE P.NF NOT IN (SELECT DISTINCT P.NF
						FROM PED P
						WHERE P.NA NOT IN (SELECT DISTINCT P.NA
												FROM PED P
												WHERE P.NP LIKE 'P1'));