-- EJERCICIO 14 --
-- FABRICAS QUE USAN AL MENOS UN ARTICULO SUMINISTRADO POR P1 --

SELECT DISTINCT P.NF
	FROM PED P
	WHERE P.NA IN (SELECT P.NA
						FROM PED P
						WHERE P.NP = 'P1');
								
-- EJERCICIO 15 --
-- PROVEEDORES QUE SUMINISTRAN AL MENOS UN ARTICULO SUMINISTRADO POR AL MENOS OTRO PROVEEDOR QUE SUMINISTRA AL MENOS UN ARTICULO AZUL --

SELECT DISTINCT P.NP
	FROM PED P
	WHERE P.NA IN (SELECT P.NA
						FROM PED P
						WHERE P.NP IN (SELECT DISTINCT P.NP
											FROM PED P, ART A
											WHERE A.NA = P.NA AND A.COLOR LIKE 'AZUL'));

-- EJERCICIO 16 --
-- PROVEEDORES QUE SUMINISTRAN A F1 Y F2 --

SELECT DISTINCT P.NP
	FROM PED P
	WHERE P.NF LIKE 'F1'
INTERSECT
SELECT DISTINCT P.NP
	FROM PED P
	WHERE P.NF LIKE 'F2';

-- PROVEEDORES QUE SUMINISTRAN A F1 O F2 --

SELECT DISTINCT P.NP
	FROM PED P
	WHERE P.NF LIKE 'F1'
UNION -- PODEMOS PONER UNION ALL PARA MOSTRAR LOS REPETIDOS --
SELECT DISTINCT P.NP
	FROM PED P
	WHERE P.NF LIKE 'F2';