USE COMERCIAL;

-- EJERCICIO 1 --
-- SELECCIONA LOS NOMBRES DE LAS F�BRICAS SITUADAS EN MADRID --

SELECT NOMF 
	FROM FAB 
	WHERE CIUDADF = 'MADRID';

-- EJERCICIO 2 --
-- SACAR LOS PROVEEDORES QUE SUMINISTRAN A F1 --

SELECT NP 
	FROM PED 
	WHERE NF = 'F1';

-- EJERCICIO 3 --
-- SACAR LOS PROVEEDORES QUE SUMINISTRAN A F1 EL ART�CULO A1 --

SELECT NP 
	FROM PED 
	WHERE NF = 'F1' AND NA = 'A1';