DROP DATABASE IF EXISTS CLAVES;
CREATE DATABASE CLAVES;
USE CLAVES;

CREATE TABLE ALUMNO
(
	DNIA INT(9) PRIMARY KEY,
	NOMRBEA VARCHAR(20),
	CURSO VARCHAR(5),
	DNIP INT(9)
);

CREATE TABLE PROFE
(
	DNIP INT(9) PRIMARY KEY,
	NOMBREP VARCHAR(20)
);

ALTER TABLE ALUMNO
	ADD CONSTRAINT FK_ALUMNO_PROFE FOREIGN KEY(DNIP)
		REFERENCES PROFE(DNIP);