DROP DATABASE IF EXISTS EJER6;
CREATE DATABASE EJER6;
USE EJER6;

CREATE TABLE CLIENTE
(
	COD_C INT PRIMARY KEY,
	COD_R INT NOT NULL
);

CREATE TABLE RESERVA
(
	COD_R INT PRIMARY KEY,
	COD_CO INT NOT NULL,
	FECHA_COMIENZO DATE NOT NULL,
	FECHA_TERMINACION DATE NOT NULL
);

CREATE TABLE AGENCIA
(
	COD_A INT PRIMARY KEY,
	COD_R INT NOT NULL
);

CREATE TABLE COCHES
(
	COD_CO INT PRIMARY KEY
);

CREATE TABLE GARAJE
(
	COD_G INT PRIMARY KEY,
	COD_CO INT NOT NULL UNIQUE
);

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_RESERVA FOREIGN KEY(COD_R)
		REFERENCES RESERVA(COD_R);
		
ALTER TABLE AGENCIA
	ADD CONSTRAINT FK_AGENCIA_RESERVA FOREIGN KEY(COD_R)
		REFERENCES RESERVA(COD_R);
		
ALTER TABLE RESERVA 
	ADD CONSTRAINT FK_RESERVA_COCHES FOREIGN KEY(COD_CO)
		REFERENCES COCHES(COD_CO);

ALTER TABLE GARAJE
	ADD CONSTRAINT FK_GARAJE_COCHES FOREIGN KEY(COD_CO)
		REFERENCES COCHES(COD_CO);