DROP DATABASE IF EXISTS INSTITUTO;
CREATE DATABASE INSTITUTO;
USE INSTITUTO;

CREATE TABLE ALUMNO
(
	DNIA INT PRIMARY KEY,
	NOMBREA VARCHAR(20) NOT NULL,
	CURSO VARCHAR(30) NOT NULL,
	TLF INT(9),
	DNIP INT
);

CREATE TABLE PROFESOR
(
	DNIP INT,
	NOMBREP VARCHAR(20) NOT NULL,
	CURSO VARCHAR(30) NOT NULL,
	CONSTRAINT PK_PROFESOR_DNIP PRIMARY KEY(DNIP)
);

DESC ALUMNO;
DESC PROFESOR;

ALTER TABLE PROFESOR
	ADD COLUMN TLF INT(9) NOT NULL;

ALTER TABLE ALUMNO
	ADD CONSTRAINT FK_ALUMNO_PROFESOR FOREIGN KEY(DNIP)
		REFERENCES PROFESOR(DNIP)
		ON DELETE CASCADE
		ON UPDATE CASCADE;
		
DESC ALUMNO;
DESC PROFESOR;

ALTER TABLE PROFESOR
	MODIFY NOMBREP VARCHAR(30),
	CHANGE CURSO CLASES VARCHAR(30);

RENAME TABLE ALUMNO TO ALUMN;

DESC ALUMN;
DESC PROFESOR;