DROP DATABASE IF EXISTS CINE;
CREATE DATABASE CINE;
USE CINE;

CREATE TABLE CINE
(
    COD_C INT NOT NULL,
    NOMBREC VARCHAR(10),
    DIRECCION VARCHAR(20),
    TELEFONO INT(9),
    DNI INT,
    CHECK (NOMBREC != 'CINE1' OR NOMBREC != 'CINE2')
);

CREATE TABLE CLIENTE
(
    DNI INT,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDOS VARCHAR(20) NOT NULL,
    EDAD INT,
    TELEFONO INT(9),
    BEBIDAS INT,
    PALOMITAS INT,
    CONSTRAINT PK_CLIENTE_DNI PRIMARY KEY(DNI),
    CONSTRAINT UQ_TELEFONO UNIQUE(TELEFONO)
);

CREATE TABLE PELICULA
(
    NOMBREP VARCHAR(10),
    DURACION INT DEFAULT 2,
    FECHASALIDA DATE,
    COD_C INT NOT NULL
);

ALTER TABLE CINE
    ADD CONSTRAINT PK_CINE_COD_C PRIMARY KEY(COD_C),
    MODIFY DIRECCION VARCHAR(30),
    CHANGE TELEFONO TLF VARCHAR(9),
    ADD CONSTRAINT FK_CINE_CLIENTE FOREIGN KEY(DNI)
            REFERENCES CLIENTE(DNI)
            ON UPDATE CASCADE
            ON DELETE CASCADE;

ALTER TABLE PELICULA
    ADD CONSTRAINT PK_PELICULA_NOMBREP PRIMARY KEY(NOMBREP),
    MODIFY DURACION INT NOT NULL,
    MODIFY FECHASALIDA DATE NOT NULL,
    ADD CONSTRAINT FK_PELICULA_CINE FOREIGN KEY(COD_C)
            REFERENCES CINE(COD_C)
            ON UPDATE CASCADE
            ON DELETE CASCADE;

ALTER TABLE CLIENTE
    ADD CONSTRAINT CK_EDAD CHECK(EDAD > 18);