-- ASIGNAR VALOR OPC-A
SET @vUsu = 10;

-- VISUALIZAR CONTENIDO
SELECT @vUsu;

-- ASIGNAR VALOR OPC-B
SELECT @vUsu := MIN(preciohora)
                FROM MAQUINAS;

-- VISUALIZAR CONTENIDO
SELECT @vUsu;

-- CASO REAL
-- MOSTRAR LAS MÁQUINAS QUE TIENEN EL PRECIO MÁS BAJO

    -- PRIMERO SE ASIGNA EL VALOR DEL PRECIO MÁS BAJO A UNA VARIABLE
SELECT @vUsu := MIN(preciohora)
                FROM MAQUINAS;

    -- USAMOS ESA VARIABLE PARA COMPARARLA CON EL PRECIO DE LAS DEMÁS
SELECT *
    FROM MAQUINAS
    WHERE preciohora = @vUsu;