/*
	AÑADIR ATRIBUTO
	CAMBIAR TIPO DE UN ATRIBUTO
	CAMBIAR NOMBRE DE UN ATRIBUTO
	CLAVE FORÁNEA UPDATE CASCADE
*/
ALTER TABLE ALUMNO
	ADD (Correo VARCHAR(25)),
	MODIFY Correo VARCHAR(30),
	CHANGE Correo CorreoA VARCHAR(30),
	ADD CONSTRAINT FK_ALUMNO_PROFE FOREIGN KEY(DNIP)
		REFERENCES PROFE(DNIP) ON UPDATE CASCADE;