CREATE DATABASE PRACTICA4;
USE PRACTICA4;
DROP TABLE IF EXISTS ALUMNO, PROFE;
CREATE TABLE PROFE
(
	DNIP CHAR(9),
	NombreP VARCHAR(20),
	TF CHAR(9)
);

CREATE TABLE ALUMNO
(
	DNIA CHAR(9),
	NombreA VARCHAR(20),
	Edad INT,
	DNIP CHAR(9)
);

--AÑADO LAS RESTRICCIONES A PARTIR DE AQUÍ--
ALTER TABLE PROFE
	ADD CONSTRAINT PK_PROFE_DNIP PRIMARY KEY(DNIP),
	MODIFY NombreP VARCHAR(20) NOT NULL,
	ADD CONSTRAINT UQ_PROFE_TF UNIQUE(TF);

ALTER TABLE ALUMNO
	ADD CONSTRAINT PK_ALUMNO_DNIA PRIMARY KEY(DNIA),
	MODIFY NombreA VARCHAR(20) DEFAULT 'Jose',
	ADD CONSTRAINT CK_ALUMNO_EDAD CHECK(Edad > 18),
	ADD CONSTRAINT FK_ALUMNO_PROFE FOREIGN KEY(DNIP)
		REFERENCES PROFE(DNIP);