/*
	LA CLAVE DE PROFE VA A SER EL NUEVO ATRIBUTO CODPRO
*/

ALTER TABLE ALUMNO
	DROP FOREIGN KEY FK_ALUMNO_PROFE,
	DROP INDEX FK_ALUMNO_PROFE;

ALTER TABLE PROFE
	ADD (COD_Pro INT),
	DROP PRIMARY KEY,
	ADD CONSTRAINT PK_PROFE PRIMARY KEY(COD_Pro);
	
ALTER TABLE ALUMNO
	DROP DNIP,
	ADD COD_Pro INT,
	ADD CONSTRAINT FK_ALUMNO_PROFE FOREIGN KEY(COD_Pro)
		REFERENCES PROFE(COD_Pro);