USE PRACTICA4;
DROP TABLE PROFE, ALUMNO;
CREATE TABLE PROFE
(
	DNIP INT(9),
	NombreP VARCHAR(20) NOT NULL,
	TF CHAR(9),
	CONSTRAINT PK_DNIP PRIMARY KEY(DNIP),
	CONSTRAINT UQ_TF UNIQUE(TF)
);

CREATE TABLE ALUMNO
(
	DNIA INT(9),
	NombreA VARCHAR(20) DEFAULT "Jose",
	Edad INT,
	CONSTRAINT PK_DNIA PRIMARY KEY(DNIA),
	CHECK (Edad BETWEEN 18 AND 100)
);