USE PRACTICA4;
CREATE TABLE PROFE
(
	DNIP INT(9) PRIMARY KEY,
	NombreP VARCHAR(20) NOT NULL,
	TF CHAR(9) UNIQUE
);

CREATE TABLE ALUMNO
(
	DNIA INT(9) PRIMARY KEY,
	NombreA VARCHAR(20) DEFAULT "Jose",
	Edad INT,
	CHECK (Edad > 18)
);